### ISSUE TITLE
Make file for C.impl/Cimpl/_main.c

### ISSUE THREAD

**Issue by eddavis2** [knivd/C.impl#3]
Do you have a make file for generating a standalone interpreter, e.g., using C.impl/Cimpl/_main.c?

**Comment by knivd** [comment]
No, I haven't. I used that main.c file in a very early stage in the development and kept it there for testing just in case it needs to revert back to a standalone version, but have not used it since.
Generating a snadalone version would be relatively simple actually. It only needs editing the current main.c to go straight to the cimpl() function, and removing the links to the files in the /RIDE folder
